[2024-03-14 15:04:23,534:INFO:main: Welcome to App Logs]
[2024-03-14 15:05:33,594:INFO:main: Welcome to App Logs]
[2024-03-14 19:32:41,718:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-14 19:32:41,721:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-14 19:32:41,722:INFO:common: created directory at: artifacts]
[2024-03-14 19:32:41,724:INFO:986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 19:33:31,419:INFO:986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 19:54:56,703:INFO:main: Welcome to App Logs]
[2024-03-14 19:54:56,703:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-14 19:54:56,706:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-14 19:54:56,707:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-14 19:54:56,708:INFO:common: created directory at: artifacts]
[2024-03-14 19:54:56,708:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 19:55:23,770:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 19:55:25,302:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-15 15:42:43,174:INFO:main: Welcome to App Logs]
[2024-03-15 15:42:43,175:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-15 15:42:43,178:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-15 15:42:43,181:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:42:43,182:INFO:common: created directory at: artifacts]
[2024-03-15 15:42:43,182:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 15:43:15,761:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 15:43:17,337:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-15 16:50:57,528:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-15 16:50:57,532:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:50:57,534:INFO:common: created directory at: artifacts]
[2024-03-24 11:42:13,154:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 11:42:13,160:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 11:42:13,162:INFO:common: created directory at: artifacts]
[2024-03-24 13:52:47,651:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 13:52:47,659:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 13:52:47,663:INFO:common: created directory at: artifacts]
[2024-03-24 13:52:50,885:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 13:52:50,888:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 13:52:50,891:INFO:common: created directory at: artifacts]
[2024-03-24 13:54:06,060:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 13:54:06,064:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 13:54:06,066:INFO:common: created directory at: artifacts]
[2024-03-24 13:56:11,136:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 13:56:11,144:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 13:56:11,147:INFO:common: created directory at: artifacts]
[2024-03-24 13:59:45,148:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 13:59:45,154:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 13:59:45,157:INFO:common: created directory at: artifacts]
[2024-03-24 13:59:45,160:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-24 14:00:48,141:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-24 14:00:48,876:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-24 14:20:55,580:INFO:main: Welcome to App Logs]
[2024-03-24 14:20:55,580:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-24 14:20:55,584:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:20:55,589:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:20:55,591:INFO:common: created directory at: artifacts]
[2024-03-24 14:20:55,593:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-24 14:21:51,373:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-24 14:21:54,030:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-24 14:21:54,031:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-24 14:21:54,035:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:21:54,041:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:21:54,042:INFO:common: created directory at: artifacts]
[2024-03-24 14:21:54,043:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-24 14:21:55,073:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-24 14:21:56,139:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-24 14:21:56,786:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-24 14:40:37,619:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:40:37,628:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:40:37,633:INFO:common: created directory at: artifacts]
[2024-03-24 14:41:45,537:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:41:45,542:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:41:45,544:INFO:common: created directory at: artifacts]
[2024-03-24 14:41:45,546:INFO:common: created directory at: artifacts/training]
[2024-03-24 14:41:49,891:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:41:49,895:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:41:49,898:INFO:common: created directory at: artifacts]
[2024-03-24 14:41:49,900:INFO:common: created directory at: artifacts/training]
[2024-03-24 14:42:45,195:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:42:45,199:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:42:45,201:INFO:common: created directory at: artifacts]
[2024-03-24 14:42:45,202:INFO:common: created directory at: artifacts/training]
[2024-03-24 14:42:45,875:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-24 14:46:58,659:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:46:58,666:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:46:58,669:INFO:common: created directory at: artifacts]
[2024-03-24 14:46:58,671:INFO:common: created directory at: artifacts/training]
[2024-03-24 14:46:59,188:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-24 14:56:10,483:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:56:10,490:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:56:10,493:INFO:common: created directory at: artifacts]
[2024-03-24 14:56:10,496:INFO:common: created directory at: artifacts/training]
[2024-03-24 14:56:10,978:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 13:03:49,804:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:03:49,811:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:03:49,813:INFO:common: created directory at: artifacts]
[2024-03-25 13:03:49,815:INFO:common: created directory at: artifacts/training]
[2024-03-25 13:03:50,515:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 13:04:16,637:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:04:16,645:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:04:16,647:INFO:common: created directory at: artifacts]
[2024-03-25 13:04:16,649:INFO:common: created directory at: artifacts/training]
[2024-03-25 13:04:17,011:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 13:14:19,670:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 13:26:10,985:INFO:main: Welcome to App Logs]
[2024-03-25 13:26:10,986:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-25 13:26:10,989:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:26:10,991:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:26:10,991:INFO:common: created directory at: artifacts]
[2024-03-25 13:26:10,992:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 13:27:49,582:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 13:27:51,132:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-25 13:27:51,132:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-25 13:27:51,135:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:27:51,137:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:27:51,138:INFO:common: created directory at: artifacts]
[2024-03-25 13:27:51,138:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-25 13:27:51,870:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 13:27:52,487:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 13:27:53,562:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-25 13:27:53,563:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-25 13:27:53,566:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:27:53,568:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:27:53,568:INFO:common: created directory at: artifacts]
[2024-03-25 13:27:53,569:INFO:common: created directory at: artifacts/training]
[2024-03-25 13:27:53,845:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 13:36:57,450:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 13:36:59,019:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-25 13:59:02,494:INFO:main: Welcome to App Logs]
[2024-03-25 13:59:02,494:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-25 13:59:02,497:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:59:02,499:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:59:02,500:INFO:common: created directory at: artifacts]
[2024-03-25 13:59:02,500:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 13:59:42,438:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 13:59:43,933:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-25 13:59:43,933:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-25 13:59:43,936:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:59:43,938:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:59:43,939:INFO:common: created directory at: artifacts]
[2024-03-25 13:59:43,939:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-25 13:59:44,623:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 13:59:45,315:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 13:59:45,825:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-25 13:59:45,825:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-25 13:59:45,829:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:59:45,832:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:59:45,832:INFO:common: created directory at: artifacts]
[2024-03-25 13:59:45,833:INFO:common: created directory at: artifacts/training]
[2024-03-25 13:59:46,130:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 14:08:09,698:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 14:08:11,536:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-25 14:24:58,771:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 14:24:58,776:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 14:24:58,778:INFO:common: created directory at: artifacts]
[2024-03-25 14:24:58,780:INFO:common: created directory at: artifacts/training]
[2024-03-25 14:24:59,468:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 14:26:51,819:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 14:26:51,825:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 14:26:51,827:INFO:common: created directory at: artifacts]
[2024-03-25 14:26:51,828:INFO:common: created directory at: artifacts/training]
[2024-03-25 14:26:52,226:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 14:55:40,870:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 14:55:40,875:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 14:55:40,878:INFO:common: created directory at: artifacts]
[2024-03-25 14:55:40,880:INFO:common: created directory at: artifacts/training]
[2024-03-25 14:55:41,324:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 14:58:22,261:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 14:58:22,266:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 14:58:22,268:INFO:common: created directory at: artifacts]
[2024-03-25 14:58:22,270:INFO:common: created directory at: artifacts/training]
[2024-03-25 14:58:22,732:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 15:07:24,914:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-26 10:06:39,274:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-26 10:06:39,284:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-26 10:06:39,287:INFO:common: created directory at: artifacts]
[2024-03-26 10:06:39,291:INFO:common: created directory at: artifacts/training]
[2024-03-26 10:07:46,640:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-26 10:07:46,645:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-26 10:07:46,647:INFO:common: created directory at: artifacts]
[2024-03-26 10:07:46,649:INFO:common: created directory at: artifacts/training]
[2024-03-26 10:07:47,329:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-26 10:12:12,462:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-26 10:13:40,555:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-26 10:13:40,562:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-26 10:13:40,565:INFO:common: created directory at: artifacts]
[2024-03-26 10:13:40,567:INFO:common: created directory at: artifacts/training]
[2024-03-26 10:19:48,373:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-26 10:19:48,380:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-26 10:19:48,383:INFO:common: created directory at: artifacts]
[2024-03-26 10:19:48,385:INFO:common: created directory at: artifacts/training]
[2024-03-27 17:18:16,921:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 17:18:16,926:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 17:18:16,928:INFO:common: created directory at: artifacts]
[2024-03-27 17:18:59,222:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 17:18:59,227:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 17:18:59,230:INFO:common: created directory at: artifacts]
[2024-03-27 17:23:25,958:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 17:23:25,964:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 17:23:25,966:INFO:common: created directory at: artifacts]
[2024-03-27 17:23:58,099:INFO:common: json file saved at: scores.json]
[2024-03-27 17:25:00,084:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 17:25:00,089:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 17:25:00,092:INFO:common: created directory at: artifacts]
[2024-03-27 17:25:33,863:INFO:common: json file saved at: scores.json]
[2024-03-27 17:37:32,399:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 17:37:32,411:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 17:37:32,415:INFO:common: created directory at: artifacts]
[2024-03-27 17:38:05,527:INFO:common: json file saved at: scores.json]
[2024-03-27 17:48:37,381:WARNING:connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'TimeoutError('The write operation timed out')': /SurajKumar2235/Kideney_disease_classification.mlflow/api/2.0/mlflow-artifacts/artifacts/4da2f174c21747948310eced9b1dffa5/f7e4267cd7864228ab1d07542245d1bb/artifacts/model/data/model.keras]
[2024-03-27 21:33:59,052:INFO:main: Welcome to App Logs]
[2024-03-27 21:33:59,052:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-27 21:33:59,055:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 21:33:59,057:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 21:33:59,058:INFO:common: created directory at: artifacts]
[2024-03-27 21:33:59,058:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-27 21:33:59,058:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-27 21:33:59,061:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 21:33:59,063:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 21:33:59,064:INFO:common: created directory at: artifacts]
[2024-03-27 21:33:59,064:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-27 21:34:01,115:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-27 21:34:01,115:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-27 21:34:01,118:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 21:34:01,120:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 21:34:01,121:INFO:common: created directory at: artifacts]
[2024-03-27 21:34:01,121:INFO:common: created directory at: artifacts/training]
[2024-03-27 21:42:27,740:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-27 21:42:27,742:INFO:main: >>>>>>>>stageEvaluating Model Using Mlflow started<<<<<<<<<<<]
[2024-03-27 21:42:27,748:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 21:42:27,753:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 21:42:27,754:INFO:common: created directory at: artifacts]
[2024-03-27 21:42:57,397:INFO:common: json file saved at: scores.json]
[2024-03-27 21:42:57,398:INFO:common: json file saved at: scores.json]
[2024-03-27 21:42:58,795:ERROR:main: Could not find experiment with ID 0]
Traceback (most recent call last):
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/main.py", line 56, in <module>
    obj.main()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/pipeline/stage04_model_evluaton.py", line 21, in main
    evaluation.log_into_mlflow()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/components/model_evaluation.py", line 63, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 381, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/client.py", line 353, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 139, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 607, in create_run
    experiment = self.get_experiment(experiment_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 421, in get_experiment
    experiment = self._get_experiment(experiment_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 391, in _get_experiment
    raise MlflowException(
mlflow.exceptions.MlflowException: Could not find experiment with ID 0
[2024-03-27 22:02:20,584:INFO:main: Welcome to App Logs]
[2024-03-27 22:02:20,584:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-27 22:02:20,588:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 22:02:20,591:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 22:02:20,591:INFO:common: created directory at: artifacts]
[2024-03-27 22:02:20,591:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-27 22:02:20,592:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-27 22:02:20,594:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 22:02:20,596:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 22:02:20,597:INFO:common: created directory at: artifacts]
[2024-03-27 22:02:20,597:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-27 22:02:22,635:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-27 22:02:22,635:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-27 22:02:22,637:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 22:02:22,639:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 22:02:22,640:INFO:common: created directory at: artifacts]
[2024-03-27 22:02:22,641:INFO:common: created directory at: artifacts/training]
[2024-03-27 22:11:12,718:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-27 22:11:12,733:INFO:main: >>>>>>>>stageEvaluating Model Using Mlflow started<<<<<<<<<<<]
[2024-03-27 22:11:12,740:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 22:11:12,745:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 22:11:12,747:INFO:common: created directory at: artifacts]
[2024-03-27 22:11:42,758:INFO:common: json file saved at: scores.json]
[2024-03-27 22:11:42,759:INFO:common: json file saved at: scores.json]
[2024-03-27 22:14:00,510:WARNING:connectionpool: Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /SurajKumar2235/Kideney_disease_classification.mlflow/api/2.0/mlflow/runs/create]
[2024-03-27 22:14:33,636:WARNING:connectionpool: Retrying (Retry(total=3, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1911f4a870>: Failed to resolve 'dagshub.com' ([Errno -2] Name or service not known)")': /SurajKumar2235/Kideney_disease_classification.mlflow/api/2.0/mlflow/runs/create]
[2024-03-27 22:18:40,473:ERROR:main: must be real number, not list]
Traceback (most recent call last):
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/main.py", line 56, in <module>
    obj.main()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/pipeline/stage04_model_evluaton.py", line 21, in main
    evaluation.log_into_mlflow()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/components/model_evaluation.py", line 65, in log_into_mlflow
    mlflow.log_metrics(
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 866, in log_metrics
    return MlflowClient().log_batch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/client.py", line 1129, in log_batch
    return self._tracking_client.log_batch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 486, in log_batch
    self.store.log_batch(run_id=run_id, metrics=metrics_batch, params=[], tags=[])
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 334, in log_batch
    metric_protos = [metric.to_proto() for metric in metrics]
                     ^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/entities/metric.py", line 40, in to_proto
    metric.value = self.value
    ^^^^^^^^^^^^
TypeError: must be real number, not list
[2024-03-27 23:09:18,792:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 23:09:18,796:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 23:09:18,797:INFO:common: created directory at: artifacts]
[2024-03-27 23:09:18,798:INFO:common: created directory at: artifacts/training]
[2024-03-27 23:21:59,425:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 23:21:59,430:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 23:21:59,432:INFO:common: created directory at: artifacts]
[2024-03-27 23:22:12,938:INFO:common: json file saved at: scores.json]
[2024-03-27 23:26:13,921:WARNING:connectionpool: Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcd20094710>, 'Connection to dagshub.com timed out. (connect timeout=120)')': /SurajKumar2235/Kideney_disease_classification.mlflow/api/2.0/mlflow/runs/create]
[2024-03-27 23:30:19,755:WARNING:connectionpool: Retrying (Retry(total=3, connect=4, read=4, redirect=5, status=5)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='dagshub.com', port=443): Read timed out. (read timeout=120)")': /SurajKumar2235/Kideney_disease_classification.mlflow/api/2.0/mlflow/runs/create]
[2024-03-27 23:41:48,444:INFO:main: Welcome to App Logs]
[2024-03-27 23:41:48,444:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-27 23:41:48,445:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 23:41:48,446:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 23:41:48,447:INFO:common: created directory at: artifacts]
[2024-03-27 23:41:48,447:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-27 23:41:48,447:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-27 23:41:48,448:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 23:41:48,449:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 23:41:48,449:INFO:common: created directory at: artifacts]
[2024-03-27 23:41:48,449:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-27 23:41:49,421:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-27 23:41:49,422:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-27 23:41:49,423:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 23:41:49,424:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 23:41:49,424:INFO:common: created directory at: artifacts]
[2024-03-27 23:41:49,425:INFO:common: created directory at: artifacts/training]
[2024-03-28 14:38:37,111:INFO:main: Welcome to App Logs]
[2024-03-28 14:38:37,112:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-28 14:38:37,116:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 14:38:37,120:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 14:38:37,121:INFO:common: created directory at: artifacts]
[2024-03-28 14:38:37,122:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-28 14:38:37,122:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-28 14:38:37,126:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 14:38:37,129:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 14:38:37,130:INFO:common: created directory at: artifacts]
[2024-03-28 14:38:37,130:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 14:38:39,756:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-28 14:38:39,757:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-28 14:38:39,760:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 14:38:39,763:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 14:38:39,764:INFO:common: created directory at: artifacts]
[2024-03-28 14:38:39,767:INFO:common: created directory at: artifacts/training]
[2024-03-28 14:40:39,147:INFO:main: Welcome to App Logs]
[2024-03-28 14:40:39,147:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-28 14:40:39,151:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 14:40:39,153:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 14:40:39,153:INFO:common: created directory at: artifacts]
[2024-03-28 14:40:39,154:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-28 14:40:39,154:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-28 14:40:39,157:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 14:40:39,160:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 14:40:39,161:INFO:common: created directory at: artifacts]
[2024-03-28 14:40:39,161:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 14:40:41,471:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-28 14:40:41,471:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-28 14:40:41,474:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 14:40:41,478:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 14:40:41,479:INFO:common: created directory at: artifacts]
[2024-03-28 14:40:41,480:INFO:common: created directory at: artifacts/training]
[2024-03-28 14:54:42,581:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-28 14:54:42,583:INFO:main: >>>>>>>>stageEvaluating Model Using Mlflow started<<<<<<<<<<<]
[2024-03-28 14:54:42,593:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 14:54:42,599:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 14:54:42,601:INFO:common: created directory at: artifacts]
[2024-03-28 14:55:14,120:INFO:common: json file saved at: scores.json]
[2024-03-28 14:55:14,121:INFO:common: json file saved at: scores.json]
[2024-03-28 15:00:59,021:INFO:main: >>>>>>stage Evaluating Model Using Mlflow compleated<<<<<

x==========x]
[2024-03-28 15:04:27,349:INFO:main: Welcome to App Logs]
[2024-03-28 15:04:27,350:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-28 15:04:27,353:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 15:04:27,355:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 15:04:27,356:INFO:common: created directory at: artifacts]
[2024-03-28 15:04:27,356:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-28 15:04:27,356:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-28 15:04:27,360:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 15:04:27,364:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 15:04:27,364:INFO:common: created directory at: artifacts]
[2024-03-28 15:04:27,365:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 15:04:29,406:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-28 15:04:29,406:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-28 15:04:29,409:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 15:04:29,411:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 15:04:29,411:INFO:common: created directory at: artifacts]
[2024-03-28 15:04:29,411:INFO:common: created directory at: artifacts/training]
[2024-03-28 15:27:45,570:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-28 15:27:45,573:INFO:main: >>>>>>>>stageEvaluating Model Using Mlflow started<<<<<<<<<<<]
[2024-03-28 15:27:45,580:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 15:27:45,585:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 15:27:45,587:INFO:common: created directory at: artifacts]
[2024-03-28 15:28:18,548:INFO:common: json file saved at: scores.json]
[2024-03-28 15:28:18,549:INFO:common: json file saved at: scores.json]
[2024-03-28 15:36:11,949:INFO:main: >>>>>>stage Evaluating Model Using Mlflow compleated<<<<<

x==========x]
[2024-03-28 18:25:14,936:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 18:25:14,943:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:25:14,946:INFO:common: created directory at: artifacts]
[2024-03-28 18:25:14,948:INFO:2016028417: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:27:38,639:INFO:main: Welcome to App Logs]
[2024-03-28 18:27:38,639:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-28 18:27:38,643:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 18:27:38,646:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:27:38,646:INFO:common: created directory at: artifacts]
[2024-03-28 18:27:38,647:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:29:53,404:INFO:main: Welcome to App Logs]
[2024-03-28 18:29:53,405:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-28 18:29:53,408:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 18:29:53,410:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:29:53,410:INFO:common: created directory at: artifacts]
[2024-03-28 18:29:53,411:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 21:32:07,517:INFO:main: Welcome to App Logs]
[2024-03-28 21:32:07,517:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-28 21:32:07,520:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:32:07,522:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:32:07,523:INFO:common: created directory at: artifacts]
[2024-03-28 21:32:07,523:ERROR:main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/main.py", line 17, in <module>
    obj.main()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/pipeline/stage01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/components/data_Ingestion.py", line 65, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/zipfile/__init__.py", line 1323, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-03-28 21:33:57,578:INFO:main: Welcome to App Logs]
[2024-03-28 21:33:57,579:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-28 21:33:57,581:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:33:57,584:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:33:57,584:INFO:common: created directory at: artifacts]
[2024-03-28 21:34:39,251:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-28 21:34:39,252:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-28 21:34:39,254:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:34:39,256:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:34:39,257:INFO:common: created directory at: artifacts]
[2024-03-28 21:34:39,257:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 21:34:41,359:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-28 21:34:41,360:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-28 21:34:41,362:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:34:41,364:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:34:41,364:INFO:common: created directory at: artifacts]
[2024-03-28 21:34:41,364:INFO:common: created directory at: artifacts/training]
[2024-03-28 21:34:42,220:ERROR:main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-ct-scan-image']
Traceback (most recent call last):
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/main.py", line 43, in <module>
    obj.main()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/pipeline/stage03_modelTraining.py", line 19, in main
    training.train_valid_generator()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/components/modelTraining.py", line 32, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/keras/src/legacy/preprocessing/image.py", line 1138, in flow_from_directory
    return DirectoryIterator(
           ^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/keras/src/legacy/preprocessing/image.py", line 453, in __init__
    for subdir in sorted(os.listdir(directory)):
                         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-ct-scan-image'
[2024-03-28 21:36:14,923:INFO:main: Welcome to App Logs]
[2024-03-28 21:36:14,924:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-28 21:36:14,927:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:36:14,929:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:36:14,930:INFO:common: created directory at: artifacts]
[2024-03-28 21:36:58,531:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-28 21:36:58,531:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-28 21:36:58,537:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:36:58,541:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:36:58,542:INFO:common: created directory at: artifacts]
[2024-03-28 21:36:58,543:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 21:37:00,742:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-28 21:37:00,742:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-28 21:37:00,745:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:37:00,747:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:37:00,749:INFO:common: created directory at: artifacts]
[2024-03-28 21:37:00,749:INFO:common: created directory at: artifacts/training]
[2024-03-28 21:37:01,672:ERROR:main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-ct-scan-image']
Traceback (most recent call last):
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/main.py", line 43, in <module>
    obj.main()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/pipeline/stage03_modelTraining.py", line 19, in main
    training.train_valid_generator()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/components/modelTraining.py", line 32, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/keras/src/legacy/preprocessing/image.py", line 1138, in flow_from_directory
    return DirectoryIterator(
           ^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/keras/src/legacy/preprocessing/image.py", line 453, in __init__
    for subdir in sorted(os.listdir(directory)):
                         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-ct-scan-image'
[2024-03-28 21:39:48,270:INFO:main: Welcome to App Logs]
[2024-03-28 21:39:48,271:INFO:main: >>>>>>>>stage DATA ingestion stage started<<<<<<<<<<<]
[2024-03-28 21:39:48,276:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:39:48,278:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:39:48,279:INFO:common: created directory at: artifacts]
[2024-03-28 21:40:30,667:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-28 21:40:30,668:INFO:main: >>>>>>>>stage prepare base model started<<<<<<<<<<<]
[2024-03-28 21:40:30,670:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:40:30,673:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:40:30,673:INFO:common: created directory at: artifacts]
[2024-03-28 21:40:30,674:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 21:40:32,898:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-28 21:40:32,898:INFO:main: >>>>>>>>stage prepare base model started<<<<<<<<<<<]
[2024-03-28 21:40:32,901:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:40:32,903:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:40:32,903:INFO:common: created directory at: artifacts]
[2024-03-28 21:40:32,904:INFO:common: created directory at: artifacts/training]
[2024-03-28 21:40:34,981:ERROR:main: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 1), output.shape=(None, 2)]
Traceback (most recent call last):
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/main.py", line 43, in <module>
    obj.main()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/pipeline/stage03_modelTraining.py", line 20, in main
    training.train()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/components/modelTraining.py", line 74, in train
    self.model.fit(
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/keras/src/backend/tensorflow/nn.py", line 553, in categorical_crossentropy
    raise ValueError(
ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 1), output.shape=(None, 2)
[2024-03-28 21:44:06,786:INFO:main: Welcome to App Logs]
[2024-03-28 21:44:06,786:INFO:main: >>>>>>>>stage DATA ingestion stage started<<<<<<<<<<<]
[2024-03-28 21:44:06,789:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:44:06,791:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:44:06,792:INFO:common: created directory at: artifacts]
[2024-03-28 21:44:45,806:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-28 21:44:45,806:INFO:main: >>>>>>>>stage prepare base model started<<<<<<<<<<<]
[2024-03-28 21:44:45,809:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:44:45,811:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:44:45,811:INFO:common: created directory at: artifacts]
[2024-03-28 21:44:45,812:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 21:44:47,835:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-28 21:44:47,835:INFO:main: >>>>>>>>stage prepare base model started<<<<<<<<<<<]
[2024-03-28 21:44:47,838:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 21:44:47,840:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 21:44:47,841:INFO:common: created directory at: artifacts]
[2024-03-28 21:44:47,841:INFO:common: created directory at: artifacts/training]
[2024-03-28 21:44:49,818:ERROR:main: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 1), output.shape=(None, 2)]
Traceback (most recent call last):
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/main.py", line 43, in <module>
    obj.main()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/pipeline/stage03_modelTraining.py", line 20, in main
    training.train()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/components/modelTraining.py", line 75, in train
    self.model.fit(
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/keras/src/backend/tensorflow/nn.py", line 553, in categorical_crossentropy
    raise ValueError(
ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 1), output.shape=(None, 2)
[2024-03-28 22:38:45,403:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 22:38:45,408:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 22:38:45,411:INFO:common: created directory at: artifacts]
[2024-03-28 22:38:45,413:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 22:39:19,347:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 22:39:19,351:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 22:39:19,354:INFO:common: created directory at: artifacts]
[2024-03-28 22:39:19,356:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 22:40:31,876:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 22:40:31,880:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 22:40:31,882:INFO:common: created directory at: artifacts]
[2024-03-28 22:40:31,884:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 22:43:15,704:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 22:43:15,726:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 22:43:15,733:INFO:common: created directory at: artifacts]
[2024-03-28 22:43:15,739:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 22:45:20,863:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 22:45:20,867:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 22:45:20,869:INFO:common: created directory at: artifacts]
[2024-03-28 22:45:20,871:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 22:47:50,918:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 22:47:50,923:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 22:47:50,925:INFO:common: created directory at: artifacts]
[2024-03-28 22:47:50,928:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 22:48:32,349:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 22:48:32,354:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 22:48:32,356:INFO:common: created directory at: artifacts]
[2024-03-28 22:48:32,358:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 22:57:35,937:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 22:57:35,944:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 22:57:35,946:INFO:common: created directory at: artifacts]
[2024-03-28 22:57:35,949:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 22:58:18,436:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 22:58:18,440:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 22:58:18,442:INFO:common: created directory at: artifacts]
[2024-03-28 22:58:18,444:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 23:00:42,041:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 23:00:42,046:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 23:00:42,048:INFO:common: created directory at: artifacts]
[2024-03-28 23:00:42,051:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 23:04:55,055:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 23:04:55,063:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 23:04:55,067:INFO:common: created directory at: artifacts]
[2024-03-28 23:04:55,069:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 23:23:10,824:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 23:23:10,831:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 23:23:10,834:INFO:common: created directory at: artifacts]
[2024-03-28 23:23:10,837:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 23:24:25,684:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 23:24:25,690:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 23:24:25,692:INFO:common: created directory at: artifacts]
[2024-03-28 23:24:25,694:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 23:25:11,635:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 23:25:11,641:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 23:25:11,643:INFO:common: created directory at: artifacts]
[2024-03-28 23:25:11,645:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 23:25:37,722:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 23:25:37,727:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 23:25:37,730:INFO:common: created directory at: artifacts]
[2024-03-28 23:25:37,731:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 23:32:02,968:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 23:32:02,975:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 23:32:02,977:INFO:common: created directory at: artifacts]
[2024-03-28 23:32:02,979:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 23:33:43,063:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 23:33:43,067:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 23:33:43,069:INFO:common: created directory at: artifacts]
[2024-03-28 23:33:43,070:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-28 23:50:02,639:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-28 23:50:02,645:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-28 23:50:02,648:INFO:common: created directory at: artifacts]
[2024-03-28 23:50:02,651:INFO:common: created directory at: artifacts/prepare_base_model]
