[2024-03-14 15:04:23,534:INFO:main: Welcome to App Logs]
[2024-03-14 15:05:33,594:INFO:main: Welcome to App Logs]
[2024-03-14 19:32:41,718:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-14 19:32:41,721:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-14 19:32:41,722:INFO:common: created directory at: artifacts]
[2024-03-14 19:32:41,724:INFO:986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 19:33:31,419:INFO:986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 19:54:56,703:INFO:main: Welcome to App Logs]
[2024-03-14 19:54:56,703:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-14 19:54:56,706:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-14 19:54:56,707:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-14 19:54:56,708:INFO:common: created directory at: artifacts]
[2024-03-14 19:54:56,708:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 19:55:23,770:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 19:55:25,302:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-15 15:42:43,174:INFO:main: Welcome to App Logs]
[2024-03-15 15:42:43,175:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-15 15:42:43,178:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-15 15:42:43,181:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:42:43,182:INFO:common: created directory at: artifacts]
[2024-03-15 15:42:43,182:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 15:43:15,761:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 15:43:17,337:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-15 16:50:57,528:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-15 16:50:57,532:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:50:57,534:INFO:common: created directory at: artifacts]
[2024-03-24 11:42:13,154:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 11:42:13,160:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 11:42:13,162:INFO:common: created directory at: artifacts]
[2024-03-24 13:52:47,651:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 13:52:47,659:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 13:52:47,663:INFO:common: created directory at: artifacts]
[2024-03-24 13:52:50,885:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 13:52:50,888:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 13:52:50,891:INFO:common: created directory at: artifacts]
[2024-03-24 13:54:06,060:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 13:54:06,064:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 13:54:06,066:INFO:common: created directory at: artifacts]
[2024-03-24 13:56:11,136:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 13:56:11,144:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 13:56:11,147:INFO:common: created directory at: artifacts]
[2024-03-24 13:59:45,148:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 13:59:45,154:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 13:59:45,157:INFO:common: created directory at: artifacts]
[2024-03-24 13:59:45,160:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-24 14:00:48,141:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-24 14:00:48,876:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-24 14:20:55,580:INFO:main: Welcome to App Logs]
[2024-03-24 14:20:55,580:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-24 14:20:55,584:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:20:55,589:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:20:55,591:INFO:common: created directory at: artifacts]
[2024-03-24 14:20:55,593:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-24 14:21:51,373:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-24 14:21:54,030:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-24 14:21:54,031:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-24 14:21:54,035:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:21:54,041:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:21:54,042:INFO:common: created directory at: artifacts]
[2024-03-24 14:21:54,043:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-24 14:21:55,073:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-24 14:21:56,139:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-24 14:21:56,786:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-24 14:40:37,619:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:40:37,628:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:40:37,633:INFO:common: created directory at: artifacts]
[2024-03-24 14:41:45,537:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:41:45,542:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:41:45,544:INFO:common: created directory at: artifacts]
[2024-03-24 14:41:45,546:INFO:common: created directory at: artifacts/training]
[2024-03-24 14:41:49,891:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:41:49,895:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:41:49,898:INFO:common: created directory at: artifacts]
[2024-03-24 14:41:49,900:INFO:common: created directory at: artifacts/training]
[2024-03-24 14:42:45,195:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:42:45,199:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:42:45,201:INFO:common: created directory at: artifacts]
[2024-03-24 14:42:45,202:INFO:common: created directory at: artifacts/training]
[2024-03-24 14:42:45,875:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-24 14:46:58,659:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:46:58,666:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:46:58,669:INFO:common: created directory at: artifacts]
[2024-03-24 14:46:58,671:INFO:common: created directory at: artifacts/training]
[2024-03-24 14:46:59,188:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-24 14:56:10,483:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-24 14:56:10,490:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-24 14:56:10,493:INFO:common: created directory at: artifacts]
[2024-03-24 14:56:10,496:INFO:common: created directory at: artifacts/training]
[2024-03-24 14:56:10,978:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 13:03:49,804:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:03:49,811:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:03:49,813:INFO:common: created directory at: artifacts]
[2024-03-25 13:03:49,815:INFO:common: created directory at: artifacts/training]
[2024-03-25 13:03:50,515:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 13:04:16,637:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:04:16,645:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:04:16,647:INFO:common: created directory at: artifacts]
[2024-03-25 13:04:16,649:INFO:common: created directory at: artifacts/training]
[2024-03-25 13:04:17,011:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 13:14:19,670:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 13:26:10,985:INFO:main: Welcome to App Logs]
[2024-03-25 13:26:10,986:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-25 13:26:10,989:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:26:10,991:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:26:10,991:INFO:common: created directory at: artifacts]
[2024-03-25 13:26:10,992:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 13:27:49,582:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 13:27:51,132:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-25 13:27:51,132:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-25 13:27:51,135:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:27:51,137:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:27:51,138:INFO:common: created directory at: artifacts]
[2024-03-25 13:27:51,138:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-25 13:27:51,870:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 13:27:52,487:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 13:27:53,562:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-25 13:27:53,563:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-25 13:27:53,566:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:27:53,568:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:27:53,568:INFO:common: created directory at: artifacts]
[2024-03-25 13:27:53,569:INFO:common: created directory at: artifacts/training]
[2024-03-25 13:27:53,845:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 13:36:57,450:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 13:36:59,019:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-25 13:59:02,494:INFO:main: Welcome to App Logs]
[2024-03-25 13:59:02,494:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-25 13:59:02,497:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:59:02,499:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:59:02,500:INFO:common: created directory at: artifacts]
[2024-03-25 13:59:02,500:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 13:59:42,438:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 13:59:43,933:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-25 13:59:43,933:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-25 13:59:43,936:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:59:43,938:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:59:43,939:INFO:common: created directory at: artifacts]
[2024-03-25 13:59:43,939:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-25 13:59:44,623:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 13:59:45,315:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 13:59:45,825:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-25 13:59:45,825:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-25 13:59:45,829:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 13:59:45,832:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 13:59:45,832:INFO:common: created directory at: artifacts]
[2024-03-25 13:59:45,833:INFO:common: created directory at: artifacts/training]
[2024-03-25 13:59:46,130:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 14:08:09,698:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-25 14:08:11,536:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-25 14:24:58,771:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 14:24:58,776:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 14:24:58,778:INFO:common: created directory at: artifacts]
[2024-03-25 14:24:58,780:INFO:common: created directory at: artifacts/training]
[2024-03-25 14:24:59,468:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 14:26:51,819:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 14:26:51,825:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 14:26:51,827:INFO:common: created directory at: artifacts]
[2024-03-25 14:26:51,828:INFO:common: created directory at: artifacts/training]
[2024-03-25 14:26:52,226:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 14:55:40,870:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 14:55:40,875:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 14:55:40,878:INFO:common: created directory at: artifacts]
[2024-03-25 14:55:40,880:INFO:common: created directory at: artifacts/training]
[2024-03-25 14:55:41,324:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 14:58:22,261:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-25 14:58:22,266:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-25 14:58:22,268:INFO:common: created directory at: artifacts]
[2024-03-25 14:58:22,270:INFO:common: created directory at: artifacts/training]
[2024-03-25 14:58:22,732:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 15:07:24,914:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-26 10:06:39,274:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-26 10:06:39,284:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-26 10:06:39,287:INFO:common: created directory at: artifacts]
[2024-03-26 10:06:39,291:INFO:common: created directory at: artifacts/training]
[2024-03-26 10:07:46,640:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-26 10:07:46,645:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-26 10:07:46,647:INFO:common: created directory at: artifacts]
[2024-03-26 10:07:46,649:INFO:common: created directory at: artifacts/training]
[2024-03-26 10:07:47,329:WARNING:saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-26 10:12:12,462:WARNING:saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-26 10:13:40,555:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-26 10:13:40,562:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-26 10:13:40,565:INFO:common: created directory at: artifacts]
[2024-03-26 10:13:40,567:INFO:common: created directory at: artifacts/training]
[2024-03-26 10:19:48,373:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-26 10:19:48,380:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-26 10:19:48,383:INFO:common: created directory at: artifacts]
[2024-03-26 10:19:48,385:INFO:common: created directory at: artifacts/training]
[2024-03-27 17:18:16,921:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 17:18:16,926:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 17:18:16,928:INFO:common: created directory at: artifacts]
[2024-03-27 17:18:59,222:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 17:18:59,227:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 17:18:59,230:INFO:common: created directory at: artifacts]
[2024-03-27 17:23:25,958:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 17:23:25,964:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 17:23:25,966:INFO:common: created directory at: artifacts]
[2024-03-27 17:23:58,099:INFO:common: json file saved at: scores.json]
[2024-03-27 17:25:00,084:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 17:25:00,089:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 17:25:00,092:INFO:common: created directory at: artifacts]
[2024-03-27 17:25:33,863:INFO:common: json file saved at: scores.json]
[2024-03-27 17:37:32,399:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 17:37:32,411:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 17:37:32,415:INFO:common: created directory at: artifacts]
[2024-03-27 17:38:05,527:INFO:common: json file saved at: scores.json]
[2024-03-27 17:48:37,381:WARNING:connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'TimeoutError('The write operation timed out')': /SurajKumar2235/Kideney_disease_classification.mlflow/api/2.0/mlflow-artifacts/artifacts/4da2f174c21747948310eced9b1dffa5/f7e4267cd7864228ab1d07542245d1bb/artifacts/model/data/model.keras]
[2024-03-27 21:33:59,052:INFO:main: Welcome to App Logs]
[2024-03-27 21:33:59,052:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-27 21:33:59,055:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 21:33:59,057:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 21:33:59,058:INFO:common: created directory at: artifacts]
[2024-03-27 21:33:59,058:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-27 21:33:59,058:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-27 21:33:59,061:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 21:33:59,063:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 21:33:59,064:INFO:common: created directory at: artifacts]
[2024-03-27 21:33:59,064:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-27 21:34:01,115:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-27 21:34:01,115:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-27 21:34:01,118:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 21:34:01,120:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 21:34:01,121:INFO:common: created directory at: artifacts]
[2024-03-27 21:34:01,121:INFO:common: created directory at: artifacts/training]
[2024-03-27 21:42:27,740:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-27 21:42:27,742:INFO:main: >>>>>>>>stageEvaluating Model Using Mlflow started<<<<<<<<<<<]
[2024-03-27 21:42:27,748:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 21:42:27,753:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 21:42:27,754:INFO:common: created directory at: artifacts]
[2024-03-27 21:42:57,397:INFO:common: json file saved at: scores.json]
[2024-03-27 21:42:57,398:INFO:common: json file saved at: scores.json]
[2024-03-27 21:42:58,795:ERROR:main: Could not find experiment with ID 0]
Traceback (most recent call last):
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/main.py", line 56, in <module>
    obj.main()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/pipeline/stage04_model_evluaton.py", line 21, in main
    evaluation.log_into_mlflow()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/components/model_evaluation.py", line 63, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 381, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/client.py", line 353, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 139, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 607, in create_run
    experiment = self.get_experiment(experiment_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 421, in get_experiment
    experiment = self._get_experiment(experiment_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 391, in _get_experiment
    raise MlflowException(
mlflow.exceptions.MlflowException: Could not find experiment with ID 0
[2024-03-27 22:02:20,584:INFO:main: Welcome to App Logs]
[2024-03-27 22:02:20,584:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-27 22:02:20,588:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 22:02:20,591:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 22:02:20,591:INFO:common: created directory at: artifacts]
[2024-03-27 22:02:20,591:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-27 22:02:20,592:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-27 22:02:20,594:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 22:02:20,596:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 22:02:20,597:INFO:common: created directory at: artifacts]
[2024-03-27 22:02:20,597:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-27 22:02:22,635:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-27 22:02:22,635:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-27 22:02:22,637:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 22:02:22,639:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 22:02:22,640:INFO:common: created directory at: artifacts]
[2024-03-27 22:02:22,641:INFO:common: created directory at: artifacts/training]
[2024-03-27 22:11:12,718:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-27 22:11:12,733:INFO:main: >>>>>>>>stageEvaluating Model Using Mlflow started<<<<<<<<<<<]
[2024-03-27 22:11:12,740:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 22:11:12,745:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 22:11:12,747:INFO:common: created directory at: artifacts]
[2024-03-27 22:11:42,758:INFO:common: json file saved at: scores.json]
[2024-03-27 22:11:42,759:INFO:common: json file saved at: scores.json]
[2024-03-27 22:14:00,510:WARNING:connectionpool: Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /SurajKumar2235/Kideney_disease_classification.mlflow/api/2.0/mlflow/runs/create]
[2024-03-27 22:14:33,636:WARNING:connectionpool: Retrying (Retry(total=3, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1911f4a870>: Failed to resolve 'dagshub.com' ([Errno -2] Name or service not known)")': /SurajKumar2235/Kideney_disease_classification.mlflow/api/2.0/mlflow/runs/create]
[2024-03-27 22:18:40,473:ERROR:main: must be real number, not list]
Traceback (most recent call last):
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/main.py", line 56, in <module>
    obj.main()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/pipeline/stage04_model_evluaton.py", line 21, in main
    evaluation.log_into_mlflow()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/components/model_evaluation.py", line 65, in log_into_mlflow
    mlflow.log_metrics(
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 866, in log_metrics
    return MlflowClient().log_batch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/client.py", line 1129, in log_batch
    return self._tracking_client.log_batch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 486, in log_batch
    self.store.log_batch(run_id=run_id, metrics=metrics_batch, params=[], tags=[])
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 334, in log_batch
    metric_protos = [metric.to_proto() for metric in metrics]
                     ^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/entities/metric.py", line 40, in to_proto
    metric.value = self.value
    ^^^^^^^^^^^^
TypeError: must be real number, not list
[2024-03-27 23:09:18,792:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 23:09:18,796:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 23:09:18,797:INFO:common: created directory at: artifacts]
[2024-03-27 23:09:18,798:INFO:common: created directory at: artifacts/training]
[2024-03-27 23:21:59,425:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 23:21:59,430:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 23:21:59,432:INFO:common: created directory at: artifacts]
[2024-03-27 23:22:12,938:INFO:common: json file saved at: scores.json]
[2024-03-27 23:26:13,921:WARNING:connectionpool: Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcd20094710>, 'Connection to dagshub.com timed out. (connect timeout=120)')': /SurajKumar2235/Kideney_disease_classification.mlflow/api/2.0/mlflow/runs/create]
[2024-03-27 23:30:19,755:WARNING:connectionpool: Retrying (Retry(total=3, connect=4, read=4, redirect=5, status=5)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='dagshub.com', port=443): Read timed out. (read timeout=120)")': /SurajKumar2235/Kideney_disease_classification.mlflow/api/2.0/mlflow/runs/create]
[2024-03-27 23:41:48,444:INFO:main: Welcome to App Logs]
[2024-03-27 23:41:48,444:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-27 23:41:48,445:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 23:41:48,446:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 23:41:48,447:INFO:common: created directory at: artifacts]
[2024-03-27 23:41:48,447:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-27 23:41:48,447:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-27 23:41:48,448:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 23:41:48,449:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 23:41:48,449:INFO:common: created directory at: artifacts]
[2024-03-27 23:41:48,449:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-27 23:41:49,421:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-27 23:41:49,422:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-27 23:41:49,423:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-27 23:41:49,424:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-27 23:41:49,424:INFO:common: created directory at: artifacts]
[2024-03-27 23:41:49,425:INFO:common: created directory at: artifacts/training]
[2024-03-29 00:00:18,057:INFO:main: Welcome to App Logs]
[2024-03-29 00:00:18,058:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-29 00:00:18,061:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:00:18,064:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:00:18,067:INFO:common: created directory at: artifacts]
[2024-03-29 00:00:18,068:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-29 00:01:19,910:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-29 00:01:21,617:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-29 00:01:21,617:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-29 00:01:21,621:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:01:21,624:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:01:21,625:INFO:common: created directory at: artifacts]
[2024-03-29 00:01:21,626:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-29 00:01:25,423:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-29 00:01:25,427:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-29 00:01:25,431:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:01:25,435:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:01:25,436:INFO:common: created directory at: artifacts]
[2024-03-29 00:01:25,439:INFO:common: created directory at: artifacts/training]
[2024-03-29 00:04:30,637:INFO:main: Welcome to App Logs]
[2024-03-29 00:04:30,638:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-29 00:04:30,642:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:04:30,646:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:04:30,647:INFO:common: created directory at: artifacts]
[2024-03-29 00:04:30,647:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-29 00:05:09,189:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-29 00:05:10,806:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-29 00:05:10,807:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-29 00:05:10,812:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:05:10,817:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:05:10,817:INFO:common: created directory at: artifacts]
[2024-03-29 00:05:10,819:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-29 00:05:13,353:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-29 00:05:13,354:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-29 00:05:13,357:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:05:13,360:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:05:13,361:INFO:common: created directory at: artifacts]
[2024-03-29 00:05:13,362:INFO:common: created directory at: artifacts/training]
[2024-03-29 00:18:25,422:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-29 00:18:25,423:INFO:main: >>>>>>>>stageEvaluating Model Using Mlflow started<<<<<<<<<<<]
[2024-03-29 00:18:25,427:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:18:25,430:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:18:25,430:INFO:common: created directory at: artifacts]
[2024-03-29 00:18:57,129:INFO:common: json file saved at: scores.json]
[2024-03-29 00:18:57,130:INFO:common: json file saved at: scores.json]
[2024-03-29 00:18:58,288:ERROR:main: Could not find experiment with ID 0]
Traceback (most recent call last):
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/main.py", line 56, in <module>
    obj.main()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/pipeline/stage04_model_evluaton.py", line 21, in main
    evaluation.log_into_mlflow()
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/src/cnnClassifier/components/model_evaluation.py", line 66, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 381, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/client.py", line 353, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 139, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 607, in create_run
    experiment = self.get_experiment(experiment_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 421, in get_experiment
    experiment = self._get_experiment(experiment_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/suraj/1366967307359354/project/KidneyClassification/Kideney_desease_classification/kidney/lib/python3.12/site-packages/mlflow/store/tracking/file_store.py", line 391, in _get_experiment
    raise MlflowException(
mlflow.exceptions.MlflowException: Could not find experiment with ID 0
[2024-03-29 00:23:01,433:INFO:main: Welcome to App Logs]
[2024-03-29 00:23:01,434:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-29 00:23:01,437:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:23:01,441:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:23:01,442:INFO:common: created directory at: artifacts]
[2024-03-29 00:23:01,442:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-29 00:24:04,140:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-29 00:24:05,866:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-29 00:24:05,867:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-29 00:24:05,871:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:24:05,874:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:24:05,874:INFO:common: created directory at: artifacts]
[2024-03-29 00:24:05,875:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-29 00:24:08,020:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-29 00:24:08,020:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-29 00:24:08,023:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:24:08,025:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:24:08,026:INFO:common: created directory at: artifacts]
[2024-03-29 00:24:08,026:INFO:common: created directory at: artifacts/training]
[2024-03-29 00:31:13,459:INFO:main: Welcome to App Logs]
[2024-03-29 00:31:13,460:INFO:main: >>>>>>>>stageDATA ingestion stage started<<<<<<<<<<<]
[2024-03-29 00:31:13,463:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:31:13,465:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:31:13,465:INFO:common: created directory at: artifacts]
[2024-03-29 00:31:13,466:INFO:data_Ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-29 00:32:18,890:INFO:data_Ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-29 00:32:20,364:INFO:main: >>>>>>stage DATA ingestion stage compleated<<<<<

x==========x]
[2024-03-29 00:32:20,364:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-29 00:32:20,367:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:32:20,369:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:32:20,370:INFO:common: created directory at: artifacts]
[2024-03-29 00:32:20,370:INFO:common: created directory at: artifacts/prepare_base_model]
[2024-03-29 00:32:22,564:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-29 00:32:22,564:INFO:main: >>>>>>>>stageprepare base model started<<<<<<<<<<<]
[2024-03-29 00:32:22,567:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:32:22,569:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:32:22,570:INFO:common: created directory at: artifacts]
[2024-03-29 00:32:22,571:INFO:common: created directory at: artifacts/training]
[2024-03-29 00:36:54,163:INFO:main: >>>>>>stage prepare base model compleated<<<<<

x==========x]
[2024-03-29 00:36:54,164:INFO:main: >>>>>>>>stageEvaluating Model Using Mlflow started<<<<<<<<<<<]
[2024-03-29 00:36:54,167:INFO:common: yaml file: config/config.yaml loaded successfully]
[2024-03-29 00:36:54,170:INFO:common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:36:54,170:INFO:common: created directory at: artifacts]
[2024-03-29 00:37:26,006:INFO:common: json file saved at: scores.json]
[2024-03-29 00:37:26,007:INFO:common: json file saved at: scores.json]
[2024-03-29 00:46:18,045:WARNING:connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'TimeoutError('The write operation timed out')': /SurajKumar2235/Kideney_disease_classification.mlflow/api/2.0/mlflow-artifacts/artifacts/4da2f174c21747948310eced9b1dffa5/331cbf232f294e89b54f560387c2febb/artifacts/model/data/model.keras]
[2024-03-29 00:59:19,656:INFO:main: >>>>>>stage Evaluating Model Using Mlflow compleated<<<<<

x==========x]
